#!/usr/bin/env bash
FILENAME=${1?Error: no filename given}
COMPONENTNAME=${2?Error: no component name given}
echo "==========================================================="
echo "Firestorm: creating component $FILENAME..."
mkdir ./components/$FILENAME
mkdir ./components/$FILENAME/client
mkdir ./components/$FILENAME/server
cp ./packages/firestorm/component-template/component.html.tmpl ./components/$FILENAME/client/$FILENAME.html
sed -i'.original' "s/TEMPLATE_NAME_GOES_HERE/$COMPONENTNAME/g" ./components/$FILENAME/client/$FILENAME.html
rm ./components/$FILENAME/client/$FILENAME.html.original
sed -i'.original' "s/TEMPLATE_NAME_GOES_HERE/$COMPONENTNAME/g" ./components/$FILENAME/client/$FILENAME.html
rm ./components/$FILENAME/client/$FILENAME.html.original
cp ./packages/firestorm/component-template/component.js.tmpl ./components/$FILENAME/client/$FILENAME.js
sed -i'.original' "s/TEMPLATE_NAME_GOES_HERE/$COMPONENTNAME/g" ./components/$FILENAME/client/$FILENAME.js
rm ./components/$FILENAME/client/$FILENAME.js.original
cp ./packages/firestorm/component-template/component.css.tmpl ./components/$FILENAME/client/$FILENAME.css
sed -i'.original' "s/TEMPLATE_NAME_GOES_HERE/$COMPONENTNAME/g" ./components/$FILENAME/client/$FILENAME.css
rm ./components/$FILENAME/client/$FILENAME.css.original
cp ./packages/firestorm/component-template/component-publications.js.tmpl ./components/$FILENAME/server/$FILENAME-publications.js
sed -i'.original' "s/TEMPLATE_NAME_GOES_HERE/$COMPONENTNAME/g" ./components/$FILENAME/server/$FILENAME-publications.js
rm ./components/$FILENAME/server/$FILENAME-publications.js.original
cp ./packages/firestorm/component-template/component-methods.js.tmpl ./components/$FILENAME/server/$FILENAME-methods.js
sed -i'.original' "s/TEMPLATE_NAME_GOES_HERE/$COMPONENTNAME/g" ./components/$FILENAME/server/$FILENAME-methods.js
rm ./components/$FILENAME/server/$FILENAME-methods.js.original
echo "COMPONENT CREATED!"
echo "Done!"
echo "==========================================================="

