#!/usr/bin/env bash
FILENAME=${1?Error: no filename given}
COLLECTIONNAME=${2?Error: no collection name given}
COLLECTIONCLASSNAME=${3?Error: no collection class name given}
MODELCLASSNAME=${4?Error: no model class name given}

echo "==========================================================="
echo "Firestorm: creating collection and model $FILENAME..."
mkdir ./lib/$FILENAME
cp ./packages/firestorm/coll-template/collection.js.tmpl ./lib/$FILENAME/$FILENAME-collection.js
sed -i'.original' "s/COLLECTION_NAME_GOES_HERE/$COLLECTIONNAME/g" ./lib/$FILENAME/$FILENAME-collection.js
rm ./lib/$FILENAME/$FILENAME-collection.js.original
sed -i'.original' "s/COLLECTION_CLASS_NAME_GOES_HERE/$COLLECTIONCLASSNAME/g" ./lib/$FILENAME/$FILENAME-collection.js
rm ./lib/$FILENAME/$FILENAME-collection.js.original
cp ./packages/firestorm/coll-template/model.js.tmpl ./lib/$FILENAME/$FILENAME-model.js
sed -i'.original' "s/MODEL_CLASS_NAME_GOES_HERE/$MODELCLASSNAME/g" ./lib/$FILENAME/$FILENAME-model.js
rm ./lib/$FILENAME/$FILENAME-model.js.original
sed -i'.original' "s/COLLECTION_CLASS_NAME_GOES_HERE/$COLLECTIONCLASSNAME/g" ./lib/$FILENAME/$FILENAME-model.js
rm ./lib/$FILENAME/$FILENAME-model.js.original
echo "COLLECTION & MODEL CREATED!"
echo "Done!"
echo "==========================================================="
