#!/usr/bin/env bash
FILENAME=${1?Error: no filename given}
PAGENAME=${2?Error: no component name given}
echo "==========================================================="
echo "Firestorm: creating page $FILENAME..."
mkdir ./pages/$FILENAME
mkdir ./pages/$FILENAME/client
mkdir ./pages/$FILENAME/server
cp ./packages/firestorm/page-template/page.html.tmpl ./pages/$FILENAME/client/$FILENAME.html
sed -i'.original' "s/TEMPLATE_NAME_GOES_HERE/$PAGENAME/g" ./pages/$FILENAME/client/$FILENAME.html
rm ./pages/$FILENAME/client/$FILENAME.html.original
sed -i'.original' "s/TEMPLATE_NAME_GOES_HERE/$PAGENAME/g" ./pages/$FILENAME/client/$FILENAME.html
rm ./pages/$FILENAME/client/$FILENAME.html.original
cp ./packages/firestorm/page-template/page.css.tmpl ./pages/$FILENAME/client/$FILENAME.css
sed -i'.original' "s/TEMPLATE_NAME_GOES_HERE/$PAGENAME/g" ./pages/$FILENAME/client/$FILENAME.css
rm ./pages/$FILENAME/client/$FILENAME.css.original
cp ./packages/firestorm/page-template/page-publications.js ./pages/$FILENAME/server/page-publications.js
sed -i'.original' "s/TEMPLATE_NAME_GOES_HERE/$PAGENAME/g" ./pages/$FILENAME/server/page-publications.js
rm ./pages/$FILENAME/server/page-publications.js.original
cp ./packages/firestorm/page-template/page.js.tmpl ./pages/$FILENAME/$FILENAME.js
sed -i'.original' "s/TEMPLATE_NAME_GOES_HERE/$PAGENAME/g" ./pages/$FILENAME/$FILENAME.js
rm ./pages/$FILENAME/$FILENAME.js.original
echo "PAGE CREATED!"
echo "IMPORTANT: Don't forget to change the the path in ./pages/$FILENAME/$FILENAME.js"
echo "IMPORTANT: Don't forget to change the the page title in ./pages/$FILENAME/$FILENAME.js"
echo "Done!"
echo "==========================================================="
